# Setup
title: "Orphan Open Source Software"
description: "Open source software abandoned by maintainers"

# About/contact
author:
  name: "Łukasz Lenart"
  url: "https://lenart.org.pl"

#Others
markdown: kramdown

theme: jekyll-theme-hacker
