# Setup
title: "Orphan Open Source Software"
description: "A place where all orphan projects can find a new home"

# About/contact
author:
  name: "Łukasz Lenart"
  url: "https://lenart.org.pl"

#Others
markdown: kramdown

theme: jekyll-theme-hacker
